name = "CharacterizeTinnitus"
uuid = "aef582c6-f511-43d4-84fb-92acabee1800"
authors = ["Nelson Barnett <nelsonvbarnett@gmail.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieAuthentication = "e115e502-7e3a-11e9-29b2-aba8be6c6778"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LibSndFile = "b13ce0c6-77b0-50c6-a2db-140568b8d1a5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
PortAudio = "80ea8bcb-4634-5cb3-8ee8-a132660d1d2d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightPostgreSQL = "4327cdd6-4902-11ea-0272-430cea0431bd"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
